version: '3'
services:

  node:
    environment:
      - APP_DB_USER
      - APP_DB_PASS
      - NODE_ENV
      - HOST
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET
      - FACEBOOK_APP_ID
      - FACEBOOK_APP_SECRET
      - INSTAGRAM_CLIENT_ID
      - INSTAGRAM_CLIENT_SECRET
      - NODE_PORT
      - DB_NAME
      - MONGO_HOST
      - MONGO_PORT
    build:
      context: ../
      dockerfile: docker/node-dockerfile
      args:
        - NODE_ENV
        - USE_SSL
        - HOST
        - NODE_PORT
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    image: 'node:1'
    volumes:
      - ${APP_VOLUME_MAPPING}

